### ISSUE TITLE
why deleting the entire git history

### ISSUE THREAD

**Issue by quantenzitrone** [auxolotl/core#16]
I'm not involved in the auxolotl project, but I saw the 303,988 additions on https://github.com/auxolotl/core/commit/072e19ee33382b9bf0789e8214084783a5a0a284 and had a conversation about this and other stuff with @jopejoe1 on the [GPN](https://gulas.ch). 
There are good arguments against deleting the git history, especially for projects as large as this:

- context from git history gets lost, like information from the commit or, that a package hasn't been updated in several years and thus still uses legacy syntax (e.g. `name` instead of `pname`) 
- authorship information gets lost

Furthermore, it should be possible to split the git history folder-wise with `git subtree split`, `git filter-branch`, `git filter-repo` and probably other tools (see git-subtree(1), git-filter-branch(1) and [the github docs](https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository)).

**Comment by Sorixelle** [comment]
This isn't intended to be a "fork" of Nixpkgs - we're trying to build a package set (and in here specifically, the foundational tooling to be able to build and compile basic packages) from scratch. Nixpkgs compatibility (at least IMO) is a non-goal. For the moment, we've been taking some of the core bits and pieces from Nixpkgs while we figure out what shape Core is going to take, which is why we have that large commit. But right now, it's not yet clear how much of that is going to remain, or how similar this codebase is going to look to Nixpkgs. Given that, I'm not convinced preserving the Git history of Nixpkgs is useful to *us*. We're not Nixpkgs, so their history isn't super useful here.

We have a [Discourse instance](https://forum.aux.computer/) for discussing topics more in depth (and something more permanent as well, since a move off GitHub to our own Forgejo instance is planned IIRC) - feel free to open a thread there if you want to start some broader discussion on the topic.

**Comment by isabelroses** [comment]
> Forgejo instance is planned

This is actually up, just needs a bit more work and were off GitHub.
